// File generated by FlutterFire CLI & customized for safe runtime fallback.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with `Firebase.initializeApp`.
///
/// Use `flutterfire configure` to overwrite options with your live Firebase Project credentials.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACIJOHK3CAylRfPQp4OrxgUZnTAA93lqs',
    appId: '1:278377966042:web:2c5a85739e3a50160478e3',
    messagingSenderId: '278377966042',
    projectId: 'pictopdf',
    authDomain: 'pictopdf.firebaseapp.com',
    storageBucket: 'pictopdf.firebasestorage.app',
    measurementId: 'G-36KE9L3YRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNE8dHHoZUUEhgkox4BzD_x5ijvZ4oQTg',
    appId: '1:278377966042:android:4223cb62475d21490478e3',
    messagingSenderId: '278377966042',
    projectId: 'pictopdf',
    storageBucket: 'pictopdf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPeChQTRdCZxzgV7X_ljexWY7tdta4eQs',
    appId: '1:278377966042:ios:3f42ff0ef74cbbdd0478e3',
    messagingSenderId: '278377966042',
    projectId: 'pictopdf',
    storageBucket: 'pictopdf.firebasestorage.app',
    iosBundleId: 'com.example.fravo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPeChQTRdCZxzgV7X_ljexWY7tdta4eQs',
    appId: '1:278377966042:ios:3f42ff0ef74cbbdd0478e3',
    messagingSenderId: '278377966042',
    projectId: 'pictopdf',
    storageBucket: 'pictopdf.firebasestorage.app',
    iosBundleId: 'com.example.fravo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACIJOHK3CAylRfPQp4OrxgUZnTAA93lqs',
    appId: '1:278377966042:web:653be521f715a8240478e3',
    messagingSenderId: '278377966042',
    projectId: 'pictopdf',
    authDomain: 'pictopdf.firebaseapp.com',
    storageBucket: 'pictopdf.firebasestorage.app',
    measurementId: 'G-GKS4GJ2J9X',
  );
}
